### ISSUE TITLE
Sincerely consult

### ISSUE THREAD

**Issue by YiDongOuYang** [salesforce/DeepTIMe#13]
Dear author, thank you for your great work! I have two questions.

1) What is the meaning of "96,192,336,720" of column "Metrics" in Table 1 in your paper?

2)I try to reproduce the experimental results through Option B. However, I get this error. Could you give me some advice?
<img width="735" alt="截屏2023-09-15 11 15 02" src="https://github.com/salesforce/DeepTime/assets/58366413/90290995-e304-43b9-87f3-88a144c7a465">

Thank you very much! I really appreciate it!

**Comment by gorold** [comment]
1. Those are forecast horizons, i.e. how many time steps to predict.
2. Have you run ```make build-all path=experiments/configs/ETTm2``` yet?

**Comment by YiDongOuYang** [comment]
Thank you very much for your swift reply!
2. Definitely! I have run make build-all path=experiments/configs/ETTm2.

**Comment by gorold** [comment]
I can't really help without more information... you can try checking whether the files indicated in the script are generated, and try to run the commands in the ```run.sh``` file directly

**Comment by YiDongOuYang** [comment]
Thank you very much! Let me have more try and provide some feedback for avoiding it from happening for other user! 
Thank you again:D

**Comment by YiDongOuYang** [comment]
I successfully solve it! I realize I unzip the all_six_datasets.zip dataset but forget to move them to the upper folder. Sorry for the time caused by me:D
