### ISSUE TITLE
Explanation of equation 1 and 2 in the paper

### ISSUE THREAD

**Issue by bcjanmay** [salesforce/DeepTime#5]
Hello,

If possible, can you please explain equations 1 and 2 in greater detail?.

A) what does super script * signify?
B) Are φ and \theta neural networks? 

I just want to understand the role of these equations. Thank you.

![image](https://user-images.githubusercontent.com/48138617/201458709-29ccdafa-7c53-4fbf-8bb8-ae4b25433467.png)

**Comment by gorold** [comment]
a) The superscript just refers to the optimal value of $\phi$ and $\theta$.

b) Somewhat, they refer to the parameters of the neural network. $f$ more specifically refers to the neural network. You can refer to section 2.2 for the specific neural network architecture used.

Hope this helps!

**Comment by bcjanmay** [comment]
Thank you very much, yes, it makes sense now.
