### ISSUE TITLE
Makefile usage

### ISSUE THREAD

**Issue by Niharikajo** [salesforce/DeepTime#6]
Hello,

Thank you for releasing the code.
I was able to recreate the results.

I am new to shell and makefile 
So, While going through the code I had a few doubts about Makefile and the shell files(run. sh)

In [Makefile](https://github.com/salesforce/DeepTime/blob/main/Makefile#L6)
```
build-all: .require-path
	for config in $(shell ls ${path}/*.gin); do \
      make build config=$$config; \
    done
 ```
1. What is the initial value of config in the for loop?

```
build: .require-config
	python -m experiments.forecast --config_path=${config} build_experiment
```
2. What is happening in the above script? 

3. While running make command i saw that the config files are again saved under storage/experiments where exactly is this mentioned in code?

In [run.sh](https://github.com/salesforce/DeepTime/blob/main/run.sh)

```
for dataset in ECL ETTm2 Exchange ILI Traffic Weather; do
  for instance in `/bin/ls -d storage/experiments/$dataset/*/*`; do
      echo $instance
      make run command=${instance}/command
  done
done
```

4. Here if the outer loop is used to move from one dataset to another(ECL, ETTm2,..), what is dataset, is it file name or variable?
5. In the inner loop what does the line `make run command=${instance}/command` do?

Please let me know.
Thanks 

Regards 
Niharika

**Comment by gorold** [comment]
1. config loops over .gin files found in the folder $path
2. it runs the function build_experiment of the class ForecastExperiment. You can take a look at experiments/forecast.py and experiments/base.py.
3. this happens in experiments/base.py, build_experiment
4. dataset is a variable, looping over ECL, ETTm2, ...
5. it calls the run task as defined in the Makefile.

Hope this helps.

**Comment by Niharikajo** [comment]
Thank you for the reply
Your answers helped me understand the code structure better

In build.py can you explain this [for loop](https://github.com/salesforce/DeepTime/blob/main/experiments/base.py#L45)? Why is it used?

```
for instance_values in tqdm(product(*variables)):
            instance_variables = dict(zip(variable_names, instance_values))
            instance_name = ','.join(['%s=%.4g' % (name.split('.')[-1], value)
                                      if isinstance(value, float)
                                      else '%s=%s' % (name.split('.')[-1], str(value).replace(' ', '_'))
                                      for name, value in instance_variables.items()])
            instance_path = os.path.join(experiment_path, instance_name)
            Path(instance_path).mkdir(parents=True, exist_ok=False)
```

Thanks

**Comment by gorold** [comment]
It loops through the cartesian product of values from the build.variables_dict dictionary from the .gin config file (from experiments/configs/...). It's used for generating multiple experiments (in storage/experiments/...) for hyperparam search, running multiple horizons, and other options. 

You might want to take a look at the [gin-config library](https://github.com/google/gin-config).

**Comment by Niharikajo** [comment]
Thank you for the answer

I had some doubt in data preprocessing

1. while calculating the [border](https://github.com/salesforce/DeepTime/blob/main/data/datasets.py#L112)  of the train/test data,

```
border1s = [0, 12 * 30 * 24 * 4 - self.lookback_len, 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4 - self.lookback_len]
border2s = [12 * 30 * 24 * 4, 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4, 12 * 30 * 24 * 4 + 8 * 30 * 24 * 4]
```
How is this calculation done, is any formula used here?

2.  In  [get_time_features](https://github.com/salesforce/DeepTime/blob/main/utils/time_features.py#L156)  a empty list is passed as an argument for features, so how and which time feature will be selected? and can we specify any feature such as MinuteOfHour or HourOfDay.


Please let me know
Thank you

**Comment by gorold** [comment]
1. This is a setting inherited from [previous work](https://github.com/zhouhaoyi/Informer2020), presumably (12, 30, 24, 4) refers to (months, days, hours, 4 periods of 15 minutes per hour).
2. As mentioned in the paper, DeepTime doesn't use time features, but we include this code for building baselines which can use it.
3. Hyperparameter search. The values in the config files are the results of hyperparam search for reproducibility. See the ```hp_search``` folder for the config files for hyperparam search.

**Comment by Niharikajo** [comment]
Thank you for the answers

Just needed a clarification,

Rephrasing the 2nd question, Where is the time index feature selected? 
In [deepTIME.py](https://github.com/salesforce/DeepTime/blob/main/models/DeepTIMe.py), [time_reprs](https://github.com/salesforce/DeepTime/blob/main/models/DeepTIMe.py#L47) are calculated are these the time index or is it selected explicitly?

Please let me know
Thank you

**Comment by nkilm** [comment]
@gorold Is this an improved model to Facebook's Prophet for time-series forecasting? [https://facebook.github.io/prophet/](https://facebook.github.io/prophet/)
P.S: I find your research to be very interesting, I'll go through your project and see if I can contribute.
